openapi: 3.0.3
info:
  title: Images Hub API
  description: Unified search API for aggregating image results from Unsplash, Pixabay, and Pexels
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
  - url: https://your-domain.com
    description: Production server

tags:
  - name: search
    description: Image search operations

paths:
  /api/images-hub/search:
    get:
      summary: Search images across multiple providers
      description: |
        Searches for images across selected providers (Unsplash, Pixabay, Pexels) and returns normalized results grouped by provider.
        
        - Calls selected providers in parallel
        - Normalizes responses into unified format
        - Groups results by provider (Unsplash → Pixabay → Pexels)
        - Handles errors gracefully (returns partial results if providers fail)
        - Supports pagination per provider
      operationId: searchImages
      tags:
        - search
      security:
        - ClerkAuth: []
      parameters:
        - name: q
          in: query
          required: true
          description: Search query string
          schema:
            type: string
            minLength: 1
            example: "sunset mountains"
        - name: providers
          in: query
          required: false
          description: Comma-separated list of providers to search (unsplash,pexels,pixabay). Defaults to all providers.
          schema:
            type: string
            default: "unsplash,pexels,pixabay"
            example: "unsplash,pexels"
        - name: page
          in: query
          required: false
          description: Page number (1-indexed) for pagination. Each provider paginates independently.
          schema:
            type: integer
            minimum: 1
            default: 1
            example: 1
        - name: per_page
          in: query
          required: false
          description: Number of results per page per provider. Maximum 200.
          schema:
            type: integer
            minimum: 1
            maximum: 200
            default: 20
            example: 20
      responses:
        '200':
          description: Successful search response with results from selected providers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
              example:
                query: "sunset mountains"
                providers:
                  - provider: "unsplash"
                    images:
                      - id: "u-abc123"
                        source: "unsplash"
                        urlThumb: "https://images.unsplash.com/photo-123?w=400"
                        urlRegular: "https://images.unsplash.com/photo-123?w=1080"
                        urlFull: "https://images.unsplash.com/photo-123"
                        width: 1920
                        height: 1080
                        description: "Beautiful sunset over mountains"
                        author: "John Doe"
                        authorUrl: "https://unsplash.com/@johndoe"
                        sourceUrl: "https://unsplash.com/photos/abc123"
                        tags: ["sunset", "mountains", "nature"]
                        attribution: "Photo by John Doe on Unsplash"
                    total: 1250
                    totalPages: 63
                    currentPage: 1
                    hasMore: true
                    error: null
                  - provider: "pixabay"
                    images:
                      - id: "pb-456789"
                        source: "pixabay"
                        urlThumb: "https://pixabay.com/get/..."
                        urlRegular: "https://pixabay.com/get/..."
                        urlFull: "https://pixabay.com/get/..."
                        width: 1920
                        height: 1080
                        description: null
                        author: "Jane Smith"
                        authorUrl: null
                        sourceUrl: "https://pixabay.com/photos/456789"
                        tags: ["sunset", "mountains"]
                        attribution: "Image by Jane Smith from Pixabay"
                    total: 2000
                    totalPages: 100
                    currentPage: 1
                    hasMore: true
                    error: null
                  - provider: "pexels"
                    images: []
                    total: 0
                    totalPages: 0
                    currentPage: 1
                    hasMore: false
                    error: "Rate limit exceeded"
                totalResults: 3250
                hasMore: true
                errors:
                  pexels: "Rate limit exceeded"
        '400':
          description: Bad request - invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Invalid query parameter"
                message: "Query parameter 'q' is required"
        '401':
          description: Unauthorized - authentication required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Unauthorized"
                message: "Authentication required"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Internal server error"
                message: "Failed to fetch images from providers"

components:
  schemas:
    ImageResult:
      type: object
      required:
        - id
        - source
        - urlThumb
        - urlRegular
        - urlFull
        - width
        - height
        - author
        - sourceUrl
        - tags
        - attribution
      properties:
        id:
          type: string
          description: Unique identifier with provider prefix (u-, px-, pb-)
          example: "u-abc123"
        source:
          type: string
          enum: [unsplash, pexels, pixabay]
          description: Provider source
          example: "unsplash"
        urlThumb:
          type: string
          format: uri
          description: Thumbnail URL (400-640px width)
          example: "https://images.unsplash.com/photo-123?w=400"
        urlRegular:
          type: string
          format: uri
          description: Regular size URL (1080-1280px width)
          example: "https://images.unsplash.com/photo-123?w=1080"
        urlFull:
          type: string
          format: uri
          description: Full-size URL (original)
          example: "https://images.unsplash.com/photo-123"
        width:
          type: integer
          description: Image width in pixels
          example: 1920
        height:
          type: integer
          description: Image height in pixels
          example: 1080
        description:
          type: string
          nullable: true
          description: Image description/alt text
          example: "Beautiful sunset over mountains"
        author:
          type: string
          description: Photographer/creator name
          example: "John Doe"
        authorUrl:
          type: string
          nullable: true
          format: uri
          description: Link to photographer's profile
          example: "https://unsplash.com/@johndoe"
        sourceUrl:
          type: string
          format: uri
          description: Link to image on provider site
          example: "https://unsplash.com/photos/abc123"
        tags:
          type: array
          items:
            type: string
          description: Array of tags/keywords
          example: ["sunset", "mountains", "nature"]
        attribution:
          type: string
          description: Formatted attribution text
          example: "Photo by John Doe on Unsplash"
    
    ProviderResult:
      type: object
      required:
        - provider
        - images
        - total
        - totalPages
        - currentPage
        - hasMore
        - error
      properties:
        provider:
          type: string
          enum: [unsplash, pexels, pixabay]
          description: Provider name
          example: "unsplash"
        images:
          type: array
          items:
            $ref: '#/components/schemas/ImageResult'
          description: Array of normalized image results
        total:
          type: integer
          description: Total results available from provider
          example: 1250
        totalPages:
          type: integer
          description: Total pages available
          example: 63
        currentPage:
          type: integer
          description: Current page number
          example: 1
        hasMore:
          type: boolean
          description: Whether more pages are available
          example: true
        error:
          type: string
          nullable: true
          description: Error message if provider failed
          example: null
    
    SearchResponse:
      type: object
      required:
        - query
        - providers
        - totalResults
        - hasMore
        - errors
      properties:
        query:
          type: string
          description: Original search query
          example: "sunset mountains"
        providers:
          type: array
          items:
            $ref: '#/components/schemas/ProviderResult'
          description: Results grouped by provider (ordered: Unsplash → Pixabay → Pexels)
        totalResults:
          type: integer
          description: Total images across all providers
          example: 3250
        hasMore:
          type: boolean
          description: Whether more results available from any provider
          example: true
        errors:
          type: object
          additionalProperties:
            type: string
          description: Provider-specific errors (provider name -> error message)
          example:
            pexels: "Rate limit exceeded"
    
    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error type
          example: "Bad Request"
        message:
          type: string
          description: Error message
          example: "Query parameter 'q' is required"
  
  securitySchemes:
    ClerkAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Clerk authentication token

